Mutation:
  type: object
  config:
    fields:
      AddApartment:
        type: ApartmentOutput
        resolve: "@=mutation('add_apartment', [args['input']])"
        args:
          input:
            type: ApartmentInput!

ApartmentOutput:
  type: object
  config:
    description: "Apartment added"
    fields:
      id:
        type: "Int!"

ApartmentInput:
  type: input-object
  config:
    description: "An apartment"
    fields:
      street_address:
        type: "String"
        description: "Address of the apartment"
      country:
        type: "String"
        description: "Country of the Apartment"
      city:
        type: "String"
        description: "City of the Apartment"
      zipcode:
        type: "String"
        description: "Zipcode of the Apartment"
      build_year:
        type: "Int"
        description: "Build year of the Apartment"
      size:
        type: "Int"
        description: "Size of the Apartment"