Query:
  type: object
  config:
    description: "Apartments ORM repository"
    fields:
      apartment:
        type: "Apartment"
        args:
          id:
            description: "Resolves using apartment id"
            type: "Int"
        resolve: "@=resolver('Apartment', [args])"
      apartment_list:
        type: "ApartmentList"
        args:
          limit:
              description: "Max count of Apartments"
              type: "Int"
        resolve: "@=resolver('ApartmentList', [args])"